name: flunet

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - pytorch=2.1.*
  - torchvision=0.16.*
  - pytorch-lightning=2.1.*
  - torchmetrics=1.2.*
  - hydra-core=1.3.*
  - pre-commit=3.5.*
  - pytest=7.*
  - rich=13.*

  # --------- loggers --------- #
  - wandb=1.* 
  
  - pip>=23.3
  - pip:
      - hydra-optuna-sweeper
      - hydra-colorlog
      - pyrootutils